# This file is managed by 'repo_helper'. Don't edit it directly.
---

os: linux
language: python
dist: focal
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

arch:
  - amd64
  - arm64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox -vv
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi


jobs:
  allow_failures:
    - arch: arm64
  exclude:
    - python: '3.7'
      arch: arm64
    - python: '3.8'
      arch: arm64
    - python: '3.9'
      arch: arm64

  include:
    - stage: test
      dist: bionic
      python: 3.8

    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/octo-api
        provider: pypi
        username: "DomDF"
        password:
          secure: pngO2Qh2lQLBTzR5na0IOD4vwPg60GmQ71yTMSeiY5DM/9zfEpEsW4q7M9ejjT1o12ETF+5V1mDEwHZ9jIaHsfT8J5dQVIHTJWR2FIdilO6uZlCtX42MULhVa6123xYTEr8bWXAmEgQK2f5r67GirHQ/1ytpen1JnqDuZWzBPXinatL0ACYSaJQD1pXO+0XGad4NKNYg0FYxU1MbnbOAqy3SQDKgf92OuLqgN+7vG3S7Vj1AJcnEc1DQ8Oopo3PYzUXg74sUKQCd46p/nDcUFA9mKxAV/EG0LN7NwmMyW4w4qxq+CzhRj1aY+fpJTAekRlYWGf7/5YiKRCRsaYiRL9SGURyOctYXfZhKI/NUpyyU2hGzQVWF+FGVFlAMTrExeeiqxrcTq5CJVj1B0CrsDCghJyxtocQifF8WUbwxpGqo4VaJins9cY4/Vg38pQ8nkxH1q7FeJLe8AslQ11LG7NM0T73lFqOwI4iHnMT5EDS2je6/zboarQC9xXNRML3sgdtJS9xiR4m7gAuwGdXeP9kKRL9X0eYIDGIzkdLOFFCreqDnxFwBjoMdB7prG65aeLqRzPcJzKWfuwh1wFU4YpXMrg8GrTws9n9KQ5LuOKx/Or57mW1X9PbzNMErb6vdKTfXYHzDwBmFbNHCUUfGFfq29j2463ZNx8E6gPQkQjg=
        distributions: "sdist bdist_wheel"
        skip_existing: true
